USE [MKR_KAYIT_YEDEK]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EVRAK_TIPLERI](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[TabloID] [smallint] NOT NULL,
	[EvrakID] [smallint] NOT NULL,
	[EvrakAdi] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_EVRAK_TIPLERI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


