USE [MKR_KAYIT_YEDEK]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TABLOLAR](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[TabloID] [smallint] NOT NULL,
	[TabloAdi] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TABLOLAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


