SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TRIGGER [dbo].[SILINEN_KAYITLAR]
ON [dbo].[CARI_HESAP_HAREKETLERI]
AFTER DELETE
AS 
BEGIN
DECLARE @TABLOID smallint, @TABLOADI nvarchar(50), @FIRMANO tinyint, @SUBENO tinyint, @USERID tinyint, @USERADI NVARCHAR(30),
@SILINMETARIHI datetime, @EVRAKTARIHI date, @EVRAKTIP tinyint, @EVRAKSERI nvarchar(20), @EVRAKSIRA int,
@EVRAKCARIKODU nvarchar(25), @EVRAKTUTAR float

SELECT @TABLOID=51, @TABLOADI=(SELECT Tabloadi FROM [MKR_KAYIT_YEDEK].dbo.TABLOLAR WHERE TabloID=51), 
@FIRMANO=deleted.cha_firmano, @SUBENO=deleted.cha_subeno, @USERID=deleted.cha_lastup_user, @USERADI=(SELECT K.User_name FROM [MikroDB_V16].dbo.KULLANICILAR K WHERE K.User_no=@USERID),
@SILINMETARIHI=GETDATE(), @EVRAKTARIHI=deleted.cha_tarihi, @EVRAKTIP=deleted.cha_evrak_tip, @EVRAKSERI=deleted.cha_evrakno_seri, @EVRAKSIRA=deleted.cha_evrakno_sira,
@EVRAKCARIKODU=deleted.cha_kod, @EVRAKTUTAR=deleted.cha_meblag
FROM deleted

INSERT INTO [MKR_KAYIT_YEDEK].DBO.SILINEN_KAYITLAR (TabloID,TabloAdi,FirmaNo,SubeNo,UserID,UserAdi,SilinmeTarihi,EvrakTarihi,EvrakTip,EvrakSeri,EvrakSira,EvrakCariKodu,EvrakTutar)
VALUES(@TABLOID,@TABLOADI,@FIRMANO,@SUBENO,@USERID,@USERADI,@SILINMETARIHI,@EVRAKTARIHI,@EVRAKTIP,@EVRAKSERI,@EVRAKSIRA,@EVRAKCARIKODU,@EVRAKTUTAR)

END

SELECT Tabloadi FROM [MKR_KAYIT_YEDEK].dbo.TABLOLAR WHERE TabloID=51